### ISSUE TITLE
getting null pointer exception

### ISSUE THREAD

**Issue by ghost** [henrychuangtw/FB-ChatHead#3]
04-22 11:11:50.816: E/AndroidRuntime(3416): FATAL EXCEPTION: main
04-22 11:11:50.816: E/AndroidRuntime(3416): java.lang.RuntimeException: Unable to start service henrychuang.tw.chatheadmsg.ChatHeadService@5353abf4 with null: java.lang.NullPointerException
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2507)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.app.ActivityThread.access$1900(ActivityThread.java:130)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.os.Handler.dispatchMessage(Handler.java:99)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.os.Looper.loop(Looper.java:137)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.app.ActivityThread.main(ActivityThread.java:4745)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at java.lang.reflect.Method.invokeNative(Native Method)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at java.lang.reflect.Method.invoke(Method.java:511)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at dalvik.system.NativeStart.main(Native Method)
04-22 11:11:50.816: E/AndroidRuntime(3416): Caused by: java.lang.NullPointerException
04-22 11:11:50.816: E/AndroidRuntime(3416):     at henrychuang.tw.chatheadmsg.ChatHeadService.onStartCommand(ChatHeadService.java:405)
04-22 11:11:50.816: E/AndroidRuntime(3416):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2490)
04-22 11:11:50.816: E/AndroidRuntime(3416):     ... 10 more

**Comment by henrychuangtw** [comment]
Solved, thanks for report
